"""Create tweets table

Revision ID: 58c93200a740
Revises: a7bca0b683fd
Create Date: 2022-01-20 15:40:25.042146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c93200a740'
down_revision = 'a7bca0b683fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('name', sa.String(length=280), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'name')
    # ### end Alembic commands ###
