"""Create tweets table

Revision ID: f27e11e8cd17
Revises: 58c93200a740
Create Date: 2022-01-20 15:42:49.516646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27e11e8cd17'
down_revision = '58c93200a740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'desc')
    op.drop_column('tweets', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('name', sa.VARCHAR(length=280), autoincrement=False, nullable=True))
    op.add_column('tweets', sa.Column('desc', sa.VARCHAR(length=280), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
